### ISSUE TITLE
Add version label

### ISSUE THREAD

**Issue by fsciuti** [acadevmy/redis-patterns-console#2]
I suggest adding a version label next to the title.

**Comment by fathorMB** [comment]
Should be next to the title in the application header on in the browser title bar? Or in both?

**Comment by fsciuti** [comment]
I think the app's header is the right position!
Thank you so much @fathorMB ;)

**Comment by fathorMB** [comment]
Thanks to you for such fast reply! I'll submit a pull request soon ;)
